/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_65cf026ad6b037855c5867c48afed98f/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    USwitch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_65cf026ad6b037855c5867c48afed98f/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
  }
}
